on:
  push:
    branches:
      - master
    tags:
      - 'v*'
name: Deploy TT Bot
jobs:
  deploy:
    name: Deploy TT Bot
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami
